display_name: ChatMCP
package_name: chatmcp
license: Apache-2.0 license

maintainer:
  name: ""
  email: ""

priority: optional

section: x11

installed_size: 20000

dependencies:
  - libgtk-3-0

essential: false

icon: assets/logo.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Chat
  - AI

generic_name: Chat Client

categories:
  - Development
  - Utility

startup_notify: true
